services:
  - type: web
    name: techdealshub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: "3.10"
      - key: DATABASE_URL
        fromDatabase:
          name: techdealshub
          property: connectionString

databases:
  - name: techdealshub
    engine: postgres
    plan: free
    version: "15"
